language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

matrix:
    allow_failures:
        - php: 7.1
        - php: 7.2
        - php: 7.3

before_install:
    - export PHP_VERSION=$TRAVIS_PHP_VERSION

install:
    - make test-install

script:
    - make test-run

after_success:
    - bash <(curl -s https://codecov.io/bash)
