language: php

php:
    - 5.5

before_install:
    - composer self-update

install:
    - travis_retry composer install --no-interaction --dev --prefer-source

script:
    - ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
