language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
          env: CODE_COVERAGE=1

before_install:
    - export PHP_VERSION=$TRAVIS_PHP_VERSION

install:
    - make test-install

script:
    - make test-run

after_success:
    - bash <(curl -s https://codecov.io/bash)
