language: php

php:
    - 5.5

before_install:
    - composer self-update

install:
    - composer install --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
