language: minimal

matrix:
    include:
        - env: PHP_VERSION=5.5
        - env: PHP_VERSION=5.6
        - env: PHP_VERSION=7.0
        - env: PHP_VERSION=7.1
        - env: PHP_VERSION=7.2
        - env: PHP_VERSION=7.3 CODE_COVERAGE=1

install:
    - make test-install

script:
    - make test-run

after_success:
    - bash <(curl -s https://codecov.io/bash) -f clover.xml

cache:
    directories:
        - $TRAVIS_BUILD_DIR/.tmp/composer
        - $TRAVIS_BUILD_DIR/vendor
