language: php

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 5.6
        - php: 7.0

before_install:
    - composer self-update

install:
    - travis_retry composer install --no-interaction --dev --prefer-source

script:
    - composer exec phpunit -- --coverage-clover clover.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
